AsteroidOS/AsteroidOSSync

- app/src/main/java/org/asteroidos/sync/ble/MediaService.java
A small patch to fix NullPointerExceptions when fields in MediaMetadata are null.
> Fix for NPE on dereference of MediaMetadata field values

- app/src/main/java/org/asteroidos/sync/services/NLService.java
This patch whitelists `com.google.android.apps.maps` so the navigation notification can be displayed.
However, the notification strangely starts with "Quitter la navigation", which is the action button label:
> Display Google Maps notifications even if they are ongoing (fixes #46)

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/asteroidos/sync/PermissionsActivity.java
- app/src/main/java/org/asteroidos/sync/ble/WeatherService.java
- app/src/main/java/org/asteroidos/sync/fragments/PositionPickerFragment.java
- app/src/main/java/org/asteroidos/sync/services/GPSTracker.java
- app/src/main/res/layout/fragment_position_picker.xml
- app/src/main/res/values/strings.xml
* Ask for FINE Location in PermissionsActivity
* Add user position on the Weather Map
* OptIn: Allow automatically getting weather based on user Location
If this option is enabled, the half hourly sync will not use the userdefined location but instead get the Location via GPS/Network.
This can be enabled in the Weather settings dialog.
If a user decides not to use this feature the GPS will only be used while on the Position Picker to show the current position.
This still requires a bit more of testing and code review, but it's working.
> Weather Location Sync

- app/src/main/java/org/asteroidos/sync/services/SynchronizationService.java
Switched from IMPORTANCE_DEFAULT to IMPORTANCE_LOW, because since Android O DEFAULT is set as HIGH which results in notification sounds.
Google is aware of this [issue](https://issuetracker.google.com/issues/65108694), and they decided to close it as "Won't Fix (Infeasible)".
> Changed NotificationChannel on the phone to "IMPORTANCE_LOW"

- app/src/main/java/org/asteroidos/sync/services/SynchronizationService.java
Since this is a persistent notification that shows the current connection status at all time the app icon should not have a badge indicating new important notifications.
> disabled badge on app icon for 'Synchronization Service'

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/asteroidos/sync/PermissionsActivity.java
As stated in the [doze standby documentation](https://developer.android.com/training/monitoring-device-state/doze-standby#support_for_other_use_cases) 
We do this currently:
> An app can fire the `ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS` intent to take the user directly to the **Battery Optimization**, where they can add the app.
This PR proposes to switch to the following concept, as it's easier for the user and more intuitive. The only downside is that we [would have to be whitelisted by Google for our use-case](https://developer.android.com/training/monitoring-device-state/doze-standby#whitelisting-cases) if we choose to publish on Google Play.
> An app holding the `REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` permission can trigger a system dialog to let the user add the app to the …
> improved standby exclusion request

- fastlane/metadata/android/de-DE/full_description.txt
- fastlane/metadata/android/en-US/full_description.txt
As described in #98 F-Droid [changes the way short-descriptions are displayed](https://gitlab.com/fdroid/fdroidclient/merge_requests/855) 
This commit extends/changes the en-US and de-DE long descriptions to make them less redundant.
> Makes en-US and de-DE descriptions less redundant

- app/src/main/res/values-it/strings.xml
@dalz mentioned(https://github.com/AsteroidOS/AsteroidOSSync/issues/40) that the app is crashing when the language is set to Italian.
This patch should fix the issue again.
> values-it/strings.xml:Fix crash when system language is Italian.

- app/src/main/java/org/asteroidos/sync/MainActivity.java
- app/src/main/java/org/asteroidos/sync/PermissionsActivity.java
- app/src/main/java/org/asteroidos/sync/ble/ScreenshotService.java
- app/src/main/java/org/asteroidos/sync/fragments/DeviceDetailFragment.java
- app/src/main/java/org/asteroidos/sync/services/GPSTracker.java
- app/src/main/java/org/asteroidos/sync/services/SynchronizationService.java
- build.gradle
This fixes #106 but I don't have a device running API <= 9 with a functioning BLE stack. So this needs testing if it breaks storing images on Android 9 and below.
> Screenshot store with MediaStore API and cleanup

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/asteroidos/sync/PermissionsActivity.java
- app/src/main/java/org/asteroidos/sync/services/NLService.java
- app/src/main/java/org/asteroidos/sync/services/PhoneStateReceiver.java
- app/src/main/res/values/strings.xml
I had an issue where the watch would only vibrate on an incoming call. Turns out you need the READ_CALL_LOG permission as hinted by @jrtberlin.
Also the contact name wasn't shown on the watch. This is also implemented in the last commit. This part is based on https://stackoverflow.com/questions/3079365/android-retrieve-contact-name-from-phone-number.
Please let me know what you think of the code. I guess some naming changes are still needed?
Big thanks to @jrtberlin for helping me with these fixes! :)
> Fix no call notification on watch & show contact name on watch.

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/asteroidos/sync/adapters/AppInfoAdapter.java
- Addresses the package visibility issue mentioned in #114 by adding the [`QUERY_ALL_PACKAGES`](https://developer.android.com/reference/android/Manifest.permission#QUERY_ALL_PACKAGES) permission
- Reformats the `AppInfoAdapter` to be more consistent and improve readability
- Updates `AppCompat` and `Material Design`
- Increases the SDK level to 30 (Android 11)
> Android 11 (SDK 30) fixes and general improvements/updates

- app/src/main/java/org/asteroidos/sync/ble/MediaService.java
- app/src/main/java/org/asteroidos/sync/ble/NotificationService.java
- app/src/main/java/org/asteroidos/sync/ble/ScreenshotService.java
- app/src/main/java/org/asteroidos/sync/ble/TimeService.java
- app/src/main/java/org/asteroidos/sync/ble/WeatherService.java
- app/src/main/java/org/asteroidos/sync/dataobjects/Notification.java
- app/src/main/java/org/asteroidos/sync/services/SynchronizationService.java
- app/src/main/java/org/asteroidos/sync/utils/AsteroidUUIDS.java
- Separates module logic and UUID values [similar to btsyncd](https://github.com/AsteroidOS/asteroid-btsyncd/blob/2fe84c78602a33981025c3f00595b443998fd30b/common.h#L47). 
-The Battery UUID for example was provided by SweetBlue that [we want to remove](#101).
- Notifications are now in their own class
- Improves readability of the code
- Simplifies new feature introduction and enables code reuse
> patch to increase modularity

- app/src/main/java/org/asteroidos/sync/ble/MediaService.java
- app/src/main/java/org/asteroidos/sync/services/SynchronizationService.java
tbh, I am not really happy with the code. Please let me know if you have suggestions to make it easier to understand.
On Android it seems (in my case at least), we have a low volume range (0-15), while from btsyncd we get a range of (0-100). Mapping this is easy. However, depending on the increment/decrement value in the asteroid-music app, nothing may happen if the value is too small. To workaround this, just increment/decrement the value if it noticed a change in volume. Because under no circumstance we want nothing to happen when the user presses the increment/decrement button in the asteroid-music app.
~Another problem arises when the volume changes rapidly. We shouldn't report back a value to the watch, as that would confuse the receiving part. A situation illustrated below may …
> Add support for volume control.

- app/src/main/java/org/asteroidos/sync/connectivity/MediaService.java
Previously the volume would only be sent when it changed, this could cause the watch to not know the current volume.
This change effectivelly always sends the current volume as the metadata is sent when the phone connects to the watch.
> MediaService: Send volume when metadata changes.

- app/src/main/java/org/asteroidos/sync/asteroid/AsteroidBleManager.java
- app/src/main/java/org/asteroidos/sync/connectivity/TimeService.java
Comments should describe the solutions perfectly.
I can't confirm if the `removeNotificationCallback` actually solves the issue where actions are executed multiple times. But it makes sense to have it here too. Initially the idea was not to have this limit, but oh well :wink: 
You can keep this PR open if you prefer, as this issue was only observed a few times by myself.
> Sync time on connect and fix actions executed multiple times.

- app/src/main/java/org/asteroidos/sync/MainActivity.java
- app/src/main/java/org/asteroidos/sync/connectivity/WeatherService.java
- app/src/main/java/org/asteroidos/sync/fragments/DeviceDetailFragment.java
- app/src/main/java/org/asteroidos/sync/fragments/WeatherSettingsFragment.java
- app/src/main/res/layout/dialog_api_key.xml
- app/src/main/res/menu/owm_position_picker_menu.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
- Add an EditText for the user to input their own API Key.
- The Weather Service now loads the SharedPreference String for the API
key on every weather refresh to use the latest API key without
restarting the app.
> Add custom OWM API Key setting

- app/src/main/java/org/asteroidos/sync/MainActivity.java
- app/src/main/res/values/strings.xml
Having the location permission is not enough to successfully scan for watches.
Instead we need to ensure that locations are actually enabled too.
The logic is slightly changed so that Bluetooth is only enabled at app start (no need to scan when already paired).
If already paired, simply connect to the watch.
If not paired, prompt to enable location when not enabled, once enabled start scanning, else quit the app.
This solves https://github.com/AsteroidOS/AsteroidOSSync/issues/145.
> Prompt to enable location before scanning.

- app/src/main/java/org/asteroidos/sync/PermissionsActivity.java
Now this is a weird one. After another Android 12 update the app was crashing again. The log shows:
```
01-24 20:41:21.084  8811  8811 E AndroidRuntime: FATAL EXCEPTION: main
01-24 20:41:21.084  8811  8811 E AndroidRuntime: Process: org.asteroidos.sync, PID: 8811
01-24 20:41:21.084  8811  8811 E AndroidRuntime: java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for AttributionSource { uid = 10829, packageName = org.asteroidos.sync, attributionTag = null, token = android.os.BinderProxy@e7f7b8c, next = null }: GattService registerScanner
01-24 20:41:21.084  8811  8811 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
01-24 20:41:21.084  8811  8811 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2421) …
```
> PermissionsActivity: Ask for BLUETOOTH_SCAN permission too.

- app/build.gradle.kts
- app/src/main/java/org/asteroidos/sync/MainActivity.java
- app/src/main/java/org/asteroidos/sync/asteroid/AsteroidBleManager.java
- app/src/main/java/org/asteroidos/sync/fragments/DeviceListFragment.java
- app/src/main/java/org/asteroidos/sync/services/SynchronizationService.java
- fastlane/metadata/android/en-US/changelogs/23.txt
- fastlane/metadata/android/en-US/changelogs/24.txt
> Device discovery for older Android versions

- app/build.gradle.kts
The original EasyWeather library doesn't use https to access the Open Weather map, which is now required. Switch to a different package with this fix applied since the original maintainer didn't update the library to fix this issue (https://github.com/MagneFire/EasyWeather/commit/4fb154e747c472c8b24bb1468304dce97a936f00).
This provides a workaround to #175.
> gradle: Switch EasyWeather package to fix http/https issues.

- app/build.gradle.kts
- fastlane/metadata/android/en-US/changelogs/27.txt
This follows up to the recent improvements to Bluetooth on Android 12+ devices: https://github.com/AsteroidOS/AsteroidOSSync/pull/187
* Improved Android 12+ support (Thanks dv1!)
* The Bluetooth connection process has been improved.
* Translation improvements
> increase app version to 0.27

- app/src/main/java/org/asteroidos/sync/asteroid/AsteroidBleManager.java
Android 13 switched Bluetooth stack to Gabledorsche. The stack is known to crash when trying to send large payload.
related SO article: https://stackoverflow.com/questions/73772158/bluetoothgattcharacteristic-write-crashes-with-android-13
This fixes issue #192
> Properly split GATT write to fit in Android 13 BLE stack limit

- app/src/main/java/org/asteroidos/sync/connectivity/MediaService.java
I could not reproduce the issue mentioned in #209... But I've added a `null` check to prevent the issue from happening.
This may fix #209.
> MediaService: Do not attempt to add a sessions listener whenever the session manager isn't available.

- .github/workflows/android.yml
- app/build.gradle.kts
- app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
This PR adds:
- a monochromatic icon: enables themed icon support on Android 13+
- stores the `debug.apk` artifact and the linter results of GitHub Action workflows
- increases the nordic ble lib to 2.7.2
- increases JDK to Java 17
> Add adaptive icon

- app/src/main/java/org/asteroidos/sync/connectivity/SilentModeService.java
Unchecking 'Silence the phone when connected' was not returning my phone to 'vibrate mode' correctly, this change saves the state of the ringer regardless of its status during connection, allowing to correctly set it back when 'silence the phone' is unchecked.
This should address issue #148 
PS. I am not an Android developer, so let me know if this change can be done in other, more appropriate way.
> Save the state of the ringer regardless of its original status during connection to watch
